---
version: "2.1"
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=5555
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /pool/Storage/socker/kasm/profiles:/profiles #optional
      - /dev/input:/dev/input #optional
      - /run/udev/data:/run/udev/data #optional
    ports:
      - 3001:3000
      - 5555:5555
    restart: unless-stopped
